package com.neph.navigation

sealed class Routes(val route: String) {
    data object Home : Routes("home")
    data object RequestHelp : Routes("request_help")
    data object MyHelpRequests : Routes("my_help_requests")
    data object AssignedRequest : Routes("assigned_request")
    data object EmergencyInfo : Routes("emergency_info")
    data object GatheringAreas : Routes("gathering_areas")
    data object Notifications : Routes("notifications")
    data object Settings : Routes("settings")
    data object PrivacySecurity : Routes("privacy_security")
    data object Welcome : Routes("welcome")
    data object Login : Routes("login")
    data object Signup : Routes("signup")
    data object VerifyEmail : Routes("verify_email")
    data object CompleteProfile : Routes("complete_profile")
    data object ForgotPassword : Routes("forgot_password")
    data object TermsOfService : Routes("terms_of_service")
    data object PrivacyPolicy : Routes("privacy_policy")
    data object Privacy : Routes("privacy")
    data object Profile : Routes("profile")
    data object EditProfile : Routes("edit_profile")
    data object Security : Routes("security")
}
